provider:
  name: mistapi
resources:
  org:
    create:
      path: /api/v1/orgs
      method: POST
    read:
      path: /api/v1/orgs/{org_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          org_id: id