/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the JunosVrrpGroupNetworksValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JunosVrrpGroupNetworksValue{}

// JunosVrrpGroupNetworksValue struct for JunosVrrpGroupNetworksValue
type JunosVrrpGroupNetworksValue struct {
	Ip *string `json:"ip,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JunosVrrpGroupNetworksValue JunosVrrpGroupNetworksValue

// NewJunosVrrpGroupNetworksValue instantiates a new JunosVrrpGroupNetworksValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJunosVrrpGroupNetworksValue() *JunosVrrpGroupNetworksValue {
	this := JunosVrrpGroupNetworksValue{}
	return &this
}

// NewJunosVrrpGroupNetworksValueWithDefaults instantiates a new JunosVrrpGroupNetworksValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJunosVrrpGroupNetworksValueWithDefaults() *JunosVrrpGroupNetworksValue {
	this := JunosVrrpGroupNetworksValue{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *JunosVrrpGroupNetworksValue) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosVrrpGroupNetworksValue) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *JunosVrrpGroupNetworksValue) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *JunosVrrpGroupNetworksValue) SetIp(v string) {
	o.Ip = &v
}

func (o JunosVrrpGroupNetworksValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JunosVrrpGroupNetworksValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JunosVrrpGroupNetworksValue) UnmarshalJSON(data []byte) (err error) {
	varJunosVrrpGroupNetworksValue := _JunosVrrpGroupNetworksValue{}

	err = json.Unmarshal(data, &varJunosVrrpGroupNetworksValue)

	if err != nil {
		return err
	}

	*o = JunosVrrpGroupNetworksValue(varJunosVrrpGroupNetworksValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJunosVrrpGroupNetworksValue struct {
	value *JunosVrrpGroupNetworksValue
	isSet bool
}

func (v NullableJunosVrrpGroupNetworksValue) Get() *JunosVrrpGroupNetworksValue {
	return v.value
}

func (v *NullableJunosVrrpGroupNetworksValue) Set(val *JunosVrrpGroupNetworksValue) {
	v.value = val
	v.isSet = true
}

func (v NullableJunosVrrpGroupNetworksValue) IsSet() bool {
	return v.isSet
}

func (v *NullableJunosVrrpGroupNetworksValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJunosVrrpGroupNetworksValue(val *JunosVrrpGroupNetworksValue) *NullableJunosVrrpGroupNetworksValue {
	return &NullableJunosVrrpGroupNetworksValue{value: val, isSet: true}
}

func (v NullableJunosVrrpGroupNetworksValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJunosVrrpGroupNetworksValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


