/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the JunosOspfAreas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JunosOspfAreas{}

// JunosOspfAreas Junos OSPF areas
type JunosOspfAreas struct {
	IncludeLoopback *bool `json:"include_loopback,omitempty"`
	// Networks to participate in an OSPF area.  Property key is the network name
	Networks *map[string]JunosOspfAreasNetworksValue `json:"networks,omitempty"`
	// OSPF type, default (default) / stub / nssa
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JunosOspfAreas JunosOspfAreas

// NewJunosOspfAreas instantiates a new JunosOspfAreas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJunosOspfAreas() *JunosOspfAreas {
	this := JunosOspfAreas{}
	var includeLoopback bool = false
	this.IncludeLoopback = &includeLoopback
	var type_ string = "default"
	this.Type = &type_
	return &this
}

// NewJunosOspfAreasWithDefaults instantiates a new JunosOspfAreas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJunosOspfAreasWithDefaults() *JunosOspfAreas {
	this := JunosOspfAreas{}
	var includeLoopback bool = false
	this.IncludeLoopback = &includeLoopback
	var type_ string = "default"
	this.Type = &type_
	return &this
}

// GetIncludeLoopback returns the IncludeLoopback field value if set, zero value otherwise.
func (o *JunosOspfAreas) GetIncludeLoopback() bool {
	if o == nil || IsNil(o.IncludeLoopback) {
		var ret bool
		return ret
	}
	return *o.IncludeLoopback
}

// GetIncludeLoopbackOk returns a tuple with the IncludeLoopback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosOspfAreas) GetIncludeLoopbackOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeLoopback) {
		return nil, false
	}
	return o.IncludeLoopback, true
}

// HasIncludeLoopback returns a boolean if a field has been set.
func (o *JunosOspfAreas) HasIncludeLoopback() bool {
	if o != nil && !IsNil(o.IncludeLoopback) {
		return true
	}

	return false
}

// SetIncludeLoopback gets a reference to the given bool and assigns it to the IncludeLoopback field.
func (o *JunosOspfAreas) SetIncludeLoopback(v bool) {
	o.IncludeLoopback = &v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *JunosOspfAreas) GetNetworks() map[string]JunosOspfAreasNetworksValue {
	if o == nil || IsNil(o.Networks) {
		var ret map[string]JunosOspfAreasNetworksValue
		return ret
	}
	return *o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosOspfAreas) GetNetworksOk() (*map[string]JunosOspfAreasNetworksValue, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *JunosOspfAreas) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given map[string]JunosOspfAreasNetworksValue and assigns it to the Networks field.
func (o *JunosOspfAreas) SetNetworks(v map[string]JunosOspfAreasNetworksValue) {
	o.Networks = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *JunosOspfAreas) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosOspfAreas) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *JunosOspfAreas) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *JunosOspfAreas) SetType(v string) {
	o.Type = &v
}

func (o JunosOspfAreas) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JunosOspfAreas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeLoopback) {
		toSerialize["include_loopback"] = o.IncludeLoopback
	}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JunosOspfAreas) UnmarshalJSON(data []byte) (err error) {
	varJunosOspfAreas := _JunosOspfAreas{}

	err = json.Unmarshal(data, &varJunosOspfAreas)

	if err != nil {
		return err
	}

	*o = JunosOspfAreas(varJunosOspfAreas)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "include_loopback")
		delete(additionalProperties, "networks")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJunosOspfAreas struct {
	value *JunosOspfAreas
	isSet bool
}

func (v NullableJunosOspfAreas) Get() *JunosOspfAreas {
	return v.value
}

func (v *NullableJunosOspfAreas) Set(val *JunosOspfAreas) {
	v.value = val
	v.isSet = true
}

func (v NullableJunosOspfAreas) IsSet() bool {
	return v.isSet
}

func (v *NullableJunosOspfAreas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJunosOspfAreas(val *JunosOspfAreas) *NullableJunosOspfAreas {
	return &NullableJunosOspfAreas{value: val, isSet: true}
}

func (v NullableJunosOspfAreas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJunosOspfAreas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


