/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the GatewayExtraRouteValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayExtraRouteValue{}

// GatewayExtraRouteValue Property key is the destination CIDR (e.g. \"10.0.0.0/8\")
type GatewayExtraRouteValue struct {
	Via *string `json:"via,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GatewayExtraRouteValue GatewayExtraRouteValue

// NewGatewayExtraRouteValue instantiates a new GatewayExtraRouteValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayExtraRouteValue() *GatewayExtraRouteValue {
	this := GatewayExtraRouteValue{}
	return &this
}

// NewGatewayExtraRouteValueWithDefaults instantiates a new GatewayExtraRouteValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayExtraRouteValueWithDefaults() *GatewayExtraRouteValue {
	this := GatewayExtraRouteValue{}
	return &this
}

// GetVia returns the Via field value if set, zero value otherwise.
func (o *GatewayExtraRouteValue) GetVia() string {
	if o == nil || IsNil(o.Via) {
		var ret string
		return ret
	}
	return *o.Via
}

// GetViaOk returns a tuple with the Via field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayExtraRouteValue) GetViaOk() (*string, bool) {
	if o == nil || IsNil(o.Via) {
		return nil, false
	}
	return o.Via, true
}

// HasVia returns a boolean if a field has been set.
func (o *GatewayExtraRouteValue) HasVia() bool {
	if o != nil && !IsNil(o.Via) {
		return true
	}

	return false
}

// SetVia gets a reference to the given string and assigns it to the Via field.
func (o *GatewayExtraRouteValue) SetVia(v string) {
	o.Via = &v
}

func (o GatewayExtraRouteValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayExtraRouteValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Via) {
		toSerialize["via"] = o.Via
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GatewayExtraRouteValue) UnmarshalJSON(data []byte) (err error) {
	varGatewayExtraRouteValue := _GatewayExtraRouteValue{}

	err = json.Unmarshal(data, &varGatewayExtraRouteValue)

	if err != nil {
		return err
	}

	*o = GatewayExtraRouteValue(varGatewayExtraRouteValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "via")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGatewayExtraRouteValue struct {
	value *GatewayExtraRouteValue
	isSet bool
}

func (v NullableGatewayExtraRouteValue) Get() *GatewayExtraRouteValue {
	return v.value
}

func (v *NullableGatewayExtraRouteValue) Set(val *GatewayExtraRouteValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayExtraRouteValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayExtraRouteValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayExtraRouteValue(val *GatewayExtraRouteValue) *NullableGatewayExtraRouteValue {
	return &NullableGatewayExtraRouteValue{value: val, isSet: true}
}

func (v NullableGatewayExtraRouteValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayExtraRouteValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


