/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the VrfExtraRoutesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VrfExtraRoutesValue{}

// VrfExtraRoutesValue struct for VrfExtraRoutesValue
type VrfExtraRoutesValue struct {
	// Next-hop address
	Via *string `json:"via,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VrfExtraRoutesValue VrfExtraRoutesValue

// NewVrfExtraRoutesValue instantiates a new VrfExtraRoutesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVrfExtraRoutesValue() *VrfExtraRoutesValue {
	this := VrfExtraRoutesValue{}
	return &this
}

// NewVrfExtraRoutesValueWithDefaults instantiates a new VrfExtraRoutesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVrfExtraRoutesValueWithDefaults() *VrfExtraRoutesValue {
	this := VrfExtraRoutesValue{}
	return &this
}

// GetVia returns the Via field value if set, zero value otherwise.
func (o *VrfExtraRoutesValue) GetVia() string {
	if o == nil || IsNil(o.Via) {
		var ret string
		return ret
	}
	return *o.Via
}

// GetViaOk returns a tuple with the Via field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VrfExtraRoutesValue) GetViaOk() (*string, bool) {
	if o == nil || IsNil(o.Via) {
		return nil, false
	}
	return o.Via, true
}

// HasVia returns a boolean if a field has been set.
func (o *VrfExtraRoutesValue) HasVia() bool {
	if o != nil && !IsNil(o.Via) {
		return true
	}

	return false
}

// SetVia gets a reference to the given string and assigns it to the Via field.
func (o *VrfExtraRoutesValue) SetVia(v string) {
	o.Via = &v
}

func (o VrfExtraRoutesValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VrfExtraRoutesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Via) {
		toSerialize["via"] = o.Via
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VrfExtraRoutesValue) UnmarshalJSON(data []byte) (err error) {
	varVrfExtraRoutesValue := _VrfExtraRoutesValue{}

	err = json.Unmarshal(data, &varVrfExtraRoutesValue)

	if err != nil {
		return err
	}

	*o = VrfExtraRoutesValue(varVrfExtraRoutesValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "via")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVrfExtraRoutesValue struct {
	value *VrfExtraRoutesValue
	isSet bool
}

func (v NullableVrfExtraRoutesValue) Get() *VrfExtraRoutesValue {
	return v.value
}

func (v *NullableVrfExtraRoutesValue) Set(val *VrfExtraRoutesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableVrfExtraRoutesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableVrfExtraRoutesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVrfExtraRoutesValue(val *VrfExtraRoutesValue) *NullableVrfExtraRoutesValue {
	return &NullableVrfExtraRoutesValue{value: val, isSet: true}
}

func (v NullableVrfExtraRoutesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVrfExtraRoutesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


