/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the GatewayTemplateTunnelAutoProvisionSecondary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayTemplateTunnelAutoProvisionSecondary{}

// GatewayTemplateTunnelAutoProvisionSecondary struct for GatewayTemplateTunnelAutoProvisionSecondary
type GatewayTemplateTunnelAutoProvisionSecondary struct {
	NumHosts *string `json:"num_hosts,omitempty"`
	// optional, only needed if `vars_only`==`false`
	WanNames []string `json:"wan_names,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GatewayTemplateTunnelAutoProvisionSecondary GatewayTemplateTunnelAutoProvisionSecondary

// NewGatewayTemplateTunnelAutoProvisionSecondary instantiates a new GatewayTemplateTunnelAutoProvisionSecondary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayTemplateTunnelAutoProvisionSecondary() *GatewayTemplateTunnelAutoProvisionSecondary {
	this := GatewayTemplateTunnelAutoProvisionSecondary{}
	return &this
}

// NewGatewayTemplateTunnelAutoProvisionSecondaryWithDefaults instantiates a new GatewayTemplateTunnelAutoProvisionSecondary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayTemplateTunnelAutoProvisionSecondaryWithDefaults() *GatewayTemplateTunnelAutoProvisionSecondary {
	this := GatewayTemplateTunnelAutoProvisionSecondary{}
	return &this
}

// GetNumHosts returns the NumHosts field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) GetNumHosts() string {
	if o == nil || IsNil(o.NumHosts) {
		var ret string
		return ret
	}
	return *o.NumHosts
}

// GetNumHostsOk returns a tuple with the NumHosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) GetNumHostsOk() (*string, bool) {
	if o == nil || IsNil(o.NumHosts) {
		return nil, false
	}
	return o.NumHosts, true
}

// HasNumHosts returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) HasNumHosts() bool {
	if o != nil && !IsNil(o.NumHosts) {
		return true
	}

	return false
}

// SetNumHosts gets a reference to the given string and assigns it to the NumHosts field.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) SetNumHosts(v string) {
	o.NumHosts = &v
}

// GetWanNames returns the WanNames field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) GetWanNames() []string {
	if o == nil || IsNil(o.WanNames) {
		var ret []string
		return ret
	}
	return o.WanNames
}

// GetWanNamesOk returns a tuple with the WanNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) GetWanNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.WanNames) {
		return nil, false
	}
	return o.WanNames, true
}

// HasWanNames returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) HasWanNames() bool {
	if o != nil && !IsNil(o.WanNames) {
		return true
	}

	return false
}

// SetWanNames gets a reference to the given []string and assigns it to the WanNames field.
func (o *GatewayTemplateTunnelAutoProvisionSecondary) SetWanNames(v []string) {
	o.WanNames = v
}

func (o GatewayTemplateTunnelAutoProvisionSecondary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTemplateTunnelAutoProvisionSecondary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NumHosts) {
		toSerialize["num_hosts"] = o.NumHosts
	}
	if !IsNil(o.WanNames) {
		toSerialize["wan_names"] = o.WanNames
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GatewayTemplateTunnelAutoProvisionSecondary) UnmarshalJSON(data []byte) (err error) {
	varGatewayTemplateTunnelAutoProvisionSecondary := _GatewayTemplateTunnelAutoProvisionSecondary{}

	err = json.Unmarshal(data, &varGatewayTemplateTunnelAutoProvisionSecondary)

	if err != nil {
		return err
	}

	*o = GatewayTemplateTunnelAutoProvisionSecondary(varGatewayTemplateTunnelAutoProvisionSecondary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "num_hosts")
		delete(additionalProperties, "wan_names")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGatewayTemplateTunnelAutoProvisionSecondary struct {
	value *GatewayTemplateTunnelAutoProvisionSecondary
	isSet bool
}

func (v NullableGatewayTemplateTunnelAutoProvisionSecondary) Get() *GatewayTemplateTunnelAutoProvisionSecondary {
	return v.value
}

func (v *NullableGatewayTemplateTunnelAutoProvisionSecondary) Set(val *GatewayTemplateTunnelAutoProvisionSecondary) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTemplateTunnelAutoProvisionSecondary) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTemplateTunnelAutoProvisionSecondary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTemplateTunnelAutoProvisionSecondary(val *GatewayTemplateTunnelAutoProvisionSecondary) *NullableGatewayTemplateTunnelAutoProvisionSecondary {
	return &NullableGatewayTemplateTunnelAutoProvisionSecondary{value: val, isSet: true}
}

func (v NullableGatewayTemplateTunnelAutoProvisionSecondary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTemplateTunnelAutoProvisionSecondary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


