/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the GatewayTemplateTunnelPrimary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayTemplateTunnelPrimary{}

// GatewayTemplateTunnelPrimary struct for GatewayTemplateTunnelPrimary
type GatewayTemplateTunnelPrimary struct {
	Hosts []string `json:"hosts,omitempty"`
	// Only if: * `provider`== `zscaler-gre`  * `provider`== `custom-gre`
	InternalIps []string `json:"internal_ips,omitempty"`
	ProbeIps []string `json:"probe_ips,omitempty"`
	// Only if: * `provider`== `custom-ipsec`
	RemoteIds []string `json:"remote_ids,omitempty"`
	WanNames []string `json:"wan_names,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GatewayTemplateTunnelPrimary GatewayTemplateTunnelPrimary

// NewGatewayTemplateTunnelPrimary instantiates a new GatewayTemplateTunnelPrimary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayTemplateTunnelPrimary() *GatewayTemplateTunnelPrimary {
	this := GatewayTemplateTunnelPrimary{}
	return &this
}

// NewGatewayTemplateTunnelPrimaryWithDefaults instantiates a new GatewayTemplateTunnelPrimary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayTemplateTunnelPrimaryWithDefaults() *GatewayTemplateTunnelPrimary {
	this := GatewayTemplateTunnelPrimary{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelPrimary) GetHosts() []string {
	if o == nil || IsNil(o.Hosts) {
		var ret []string
		return ret
	}
	return o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelPrimary) GetHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelPrimary) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *GatewayTemplateTunnelPrimary) SetHosts(v []string) {
	o.Hosts = v
}

// GetInternalIps returns the InternalIps field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelPrimary) GetInternalIps() []string {
	if o == nil || IsNil(o.InternalIps) {
		var ret []string
		return ret
	}
	return o.InternalIps
}

// GetInternalIpsOk returns a tuple with the InternalIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelPrimary) GetInternalIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.InternalIps) {
		return nil, false
	}
	return o.InternalIps, true
}

// HasInternalIps returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelPrimary) HasInternalIps() bool {
	if o != nil && !IsNil(o.InternalIps) {
		return true
	}

	return false
}

// SetInternalIps gets a reference to the given []string and assigns it to the InternalIps field.
func (o *GatewayTemplateTunnelPrimary) SetInternalIps(v []string) {
	o.InternalIps = v
}

// GetProbeIps returns the ProbeIps field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelPrimary) GetProbeIps() []string {
	if o == nil || IsNil(o.ProbeIps) {
		var ret []string
		return ret
	}
	return o.ProbeIps
}

// GetProbeIpsOk returns a tuple with the ProbeIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelPrimary) GetProbeIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProbeIps) {
		return nil, false
	}
	return o.ProbeIps, true
}

// HasProbeIps returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelPrimary) HasProbeIps() bool {
	if o != nil && !IsNil(o.ProbeIps) {
		return true
	}

	return false
}

// SetProbeIps gets a reference to the given []string and assigns it to the ProbeIps field.
func (o *GatewayTemplateTunnelPrimary) SetProbeIps(v []string) {
	o.ProbeIps = v
}

// GetRemoteIds returns the RemoteIds field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelPrimary) GetRemoteIds() []string {
	if o == nil || IsNil(o.RemoteIds) {
		var ret []string
		return ret
	}
	return o.RemoteIds
}

// GetRemoteIdsOk returns a tuple with the RemoteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelPrimary) GetRemoteIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.RemoteIds) {
		return nil, false
	}
	return o.RemoteIds, true
}

// HasRemoteIds returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelPrimary) HasRemoteIds() bool {
	if o != nil && !IsNil(o.RemoteIds) {
		return true
	}

	return false
}

// SetRemoteIds gets a reference to the given []string and assigns it to the RemoteIds field.
func (o *GatewayTemplateTunnelPrimary) SetRemoteIds(v []string) {
	o.RemoteIds = v
}

// GetWanNames returns the WanNames field value if set, zero value otherwise.
func (o *GatewayTemplateTunnelPrimary) GetWanNames() []string {
	if o == nil || IsNil(o.WanNames) {
		var ret []string
		return ret
	}
	return o.WanNames
}

// GetWanNamesOk returns a tuple with the WanNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayTemplateTunnelPrimary) GetWanNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.WanNames) {
		return nil, false
	}
	return o.WanNames, true
}

// HasWanNames returns a boolean if a field has been set.
func (o *GatewayTemplateTunnelPrimary) HasWanNames() bool {
	if o != nil && !IsNil(o.WanNames) {
		return true
	}

	return false
}

// SetWanNames gets a reference to the given []string and assigns it to the WanNames field.
func (o *GatewayTemplateTunnelPrimary) SetWanNames(v []string) {
	o.WanNames = v
}

func (o GatewayTemplateTunnelPrimary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTemplateTunnelPrimary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.InternalIps) {
		toSerialize["internal_ips"] = o.InternalIps
	}
	if !IsNil(o.ProbeIps) {
		toSerialize["probe_ips"] = o.ProbeIps
	}
	if !IsNil(o.RemoteIds) {
		toSerialize["remote_ids"] = o.RemoteIds
	}
	if !IsNil(o.WanNames) {
		toSerialize["wan_names"] = o.WanNames
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GatewayTemplateTunnelPrimary) UnmarshalJSON(data []byte) (err error) {
	varGatewayTemplateTunnelPrimary := _GatewayTemplateTunnelPrimary{}

	err = json.Unmarshal(data, &varGatewayTemplateTunnelPrimary)

	if err != nil {
		return err
	}

	*o = GatewayTemplateTunnelPrimary(varGatewayTemplateTunnelPrimary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hosts")
		delete(additionalProperties, "internal_ips")
		delete(additionalProperties, "probe_ips")
		delete(additionalProperties, "remote_ids")
		delete(additionalProperties, "wan_names")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGatewayTemplateTunnelPrimary struct {
	value *GatewayTemplateTunnelPrimary
	isSet bool
}

func (v NullableGatewayTemplateTunnelPrimary) Get() *GatewayTemplateTunnelPrimary {
	return v.value
}

func (v *NullableGatewayTemplateTunnelPrimary) Set(val *GatewayTemplateTunnelPrimary) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTemplateTunnelPrimary) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTemplateTunnelPrimary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTemplateTunnelPrimary(val *GatewayTemplateTunnelPrimary) *NullableGatewayTemplateTunnelPrimary {
	return &NullableGatewayTemplateTunnelPrimary{value: val, isSet: true}
}

func (v NullableGatewayTemplateTunnelPrimary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTemplateTunnelPrimary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


