/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// GatewayTemplateTunnelAuthAlgo the model 'GatewayTemplateTunnelAuthAlgo'
type GatewayTemplateTunnelAuthAlgo string

// List of gateway_template_tunnel_auth_algo
const (
	GATEWAYTEMPLATETUNNELAUTHALGO_SHA1 GatewayTemplateTunnelAuthAlgo = "sha1"
	GATEWAYTEMPLATETUNNELAUTHALGO_SHA2 GatewayTemplateTunnelAuthAlgo = "sha2"
	GATEWAYTEMPLATETUNNELAUTHALGO_MD5 GatewayTemplateTunnelAuthAlgo = "md5"
)

// All allowed values of GatewayTemplateTunnelAuthAlgo enum
var AllowedGatewayTemplateTunnelAuthAlgoEnumValues = []GatewayTemplateTunnelAuthAlgo{
	"sha1",
	"sha2",
	"md5",
}

func (v *GatewayTemplateTunnelAuthAlgo) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayTemplateTunnelAuthAlgo(value)
	for _, existing := range AllowedGatewayTemplateTunnelAuthAlgoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayTemplateTunnelAuthAlgo", value)
}

// NewGatewayTemplateTunnelAuthAlgoFromValue returns a pointer to a valid GatewayTemplateTunnelAuthAlgo
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayTemplateTunnelAuthAlgoFromValue(v string) (*GatewayTemplateTunnelAuthAlgo, error) {
	ev := GatewayTemplateTunnelAuthAlgo(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayTemplateTunnelAuthAlgo: valid values are %v", v, AllowedGatewayTemplateTunnelAuthAlgoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayTemplateTunnelAuthAlgo) IsValid() bool {
	for _, existing := range AllowedGatewayTemplateTunnelAuthAlgoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to gateway_template_tunnel_auth_algo value
func (v GatewayTemplateTunnelAuthAlgo) Ptr() *GatewayTemplateTunnelAuthAlgo {
	return &v
}

type NullableGatewayTemplateTunnelAuthAlgo struct {
	value *GatewayTemplateTunnelAuthAlgo
	isSet bool
}

func (v NullableGatewayTemplateTunnelAuthAlgo) Get() *GatewayTemplateTunnelAuthAlgo {
	return v.value
}

func (v *NullableGatewayTemplateTunnelAuthAlgo) Set(val *GatewayTemplateTunnelAuthAlgo) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTemplateTunnelAuthAlgo) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTemplateTunnelAuthAlgo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTemplateTunnelAuthAlgo(val *GatewayTemplateTunnelAuthAlgo) *NullableGatewayTemplateTunnelAuthAlgo {
	return &NullableGatewayTemplateTunnelAuthAlgo{value: val, isSet: true}
}

func (v NullableGatewayTemplateTunnelAuthAlgo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTemplateTunnelAuthAlgo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

