/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the SiteSettingCriticalUrlMonitoringMonitorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteSettingCriticalUrlMonitoringMonitorsInner{}

// SiteSettingCriticalUrlMonitoringMonitorsInner struct for SiteSettingCriticalUrlMonitoringMonitorsInner
type SiteSettingCriticalUrlMonitoringMonitorsInner struct {
	Url *string `json:"url,omitempty"`
	VlanId *int32 `json:"vlan_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SiteSettingCriticalUrlMonitoringMonitorsInner SiteSettingCriticalUrlMonitoringMonitorsInner

// NewSiteSettingCriticalUrlMonitoringMonitorsInner instantiates a new SiteSettingCriticalUrlMonitoringMonitorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteSettingCriticalUrlMonitoringMonitorsInner() *SiteSettingCriticalUrlMonitoringMonitorsInner {
	this := SiteSettingCriticalUrlMonitoringMonitorsInner{}
	var vlanId int32 = 1
	this.VlanId = &vlanId
	return &this
}

// NewSiteSettingCriticalUrlMonitoringMonitorsInnerWithDefaults instantiates a new SiteSettingCriticalUrlMonitoringMonitorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteSettingCriticalUrlMonitoringMonitorsInnerWithDefaults() *SiteSettingCriticalUrlMonitoringMonitorsInner {
	this := SiteSettingCriticalUrlMonitoringMonitorsInner{}
	var vlanId int32 = 1
	this.VlanId = &vlanId
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) SetUrl(v string) {
	o.Url = &v
}

// GetVlanId returns the VlanId field value if set, zero value otherwise.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) GetVlanId() int32 {
	if o == nil || IsNil(o.VlanId) {
		var ret int32
		return ret
	}
	return *o.VlanId
}

// GetVlanIdOk returns a tuple with the VlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) GetVlanIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanId) {
		return nil, false
	}
	return o.VlanId, true
}

// HasVlanId returns a boolean if a field has been set.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) HasVlanId() bool {
	if o != nil && !IsNil(o.VlanId) {
		return true
	}

	return false
}

// SetVlanId gets a reference to the given int32 and assigns it to the VlanId field.
func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) SetVlanId(v int32) {
	o.VlanId = &v
}

func (o SiteSettingCriticalUrlMonitoringMonitorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteSettingCriticalUrlMonitoringMonitorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.VlanId) {
		toSerialize["vlan_id"] = o.VlanId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SiteSettingCriticalUrlMonitoringMonitorsInner) UnmarshalJSON(data []byte) (err error) {
	varSiteSettingCriticalUrlMonitoringMonitorsInner := _SiteSettingCriticalUrlMonitoringMonitorsInner{}

	err = json.Unmarshal(data, &varSiteSettingCriticalUrlMonitoringMonitorsInner)

	if err != nil {
		return err
	}

	*o = SiteSettingCriticalUrlMonitoringMonitorsInner(varSiteSettingCriticalUrlMonitoringMonitorsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "vlan_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSiteSettingCriticalUrlMonitoringMonitorsInner struct {
	value *SiteSettingCriticalUrlMonitoringMonitorsInner
	isSet bool
}

func (v NullableSiteSettingCriticalUrlMonitoringMonitorsInner) Get() *SiteSettingCriticalUrlMonitoringMonitorsInner {
	return v.value
}

func (v *NullableSiteSettingCriticalUrlMonitoringMonitorsInner) Set(val *SiteSettingCriticalUrlMonitoringMonitorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteSettingCriticalUrlMonitoringMonitorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteSettingCriticalUrlMonitoringMonitorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteSettingCriticalUrlMonitoringMonitorsInner(val *SiteSettingCriticalUrlMonitoringMonitorsInner) *NullableSiteSettingCriticalUrlMonitoringMonitorsInner {
	return &NullableSiteSettingCriticalUrlMonitoringMonitorsInner{value: val, isSet: true}
}

func (v NullableSiteSettingCriticalUrlMonitoringMonitorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteSettingCriticalUrlMonitoringMonitorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


