provider:
  name: mistapi
resources:
  org:
    create:
      path: /api/v1/orgs
      method: POST
    read:
      path: /api/v1/orgs/{org_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          org_id: id
  site:
    create:
      path: /api/v1/orgs/{org_id}/sites
      method: POST
    read:
      path: /api/v1/sites/{site_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          site_id: id
