provider:
  name: mistapi
resources:
  org:
    create:
      path: /api/v1/orgs
      method: POST
    read:
      path: /api/v1/orgs/{org_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          org_id: id
  site:
    create:
      path: /api/v1/orgs/{org_id}/sites
      method: POST
    read:
      path: /api/v1/sites/{site_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          site_id: id
      ignores:
        - created_time
        - modified_time
  sitegroup:
    create:
      path: /api/v1/orgs/{org_id}/sitegroups
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - site_ids
      attributes:
        aliases:
          sitegroup_id: id
  networktemplate:
    create:
      path: /api/v1/orgs/{org_id}/networktemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - import_org_networks
        - extra_routes6
        - switch_matching.rules.switch_mgmt
      attributes:
        aliases:
          networktemplate_id: id
  service:
    create:
      path: /api/v1/orgs/{org_id}/services
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          service_id: id
  network:
    create:
      path: /api/v1/orgs/{org_id}/networks
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          network_id: id
  gatewaytemplate:
    create:
      path: /api/v1/orgs/{org_id}/gatewaytemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
        - gateway_matching
        - idp_profiles.created_time
        - idp_profiles.modified_time
        - idp_profiles.id
        - networks.created_time
        - networks.modified_time
        - networks.id
        - networks.org_id
        - oob_ip_config
      attributes:
        aliases:
          gatewaytemplate_id: id
  nactag:
    create:
      path: /api/v1/orgs/{org_id}/nactags
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          nactag_id: id
      ignores:
        - created_time
        - modified_time
  nacrule:
    create:
      path: /api/v1/orgs/{org_id}/nacrules
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          nacrule_id: id
      ignores:
        - created_time
        - modified_time
  rftemplate:
    create:
      path: /api/v1/orgs/{org_id}/rftemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - band_5_on_24_radio
      attributes:
        aliases:
          rftemplate_id: id
  site_setting:
    create:
      path: /api/v1/sites/{site_id}/setting
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/setting
      method: GET
    update:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    delete:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - id
        - org_id
        - for_site
        - additional_config_cmds
        - ap_matching
        - ap_port_config
        - auto_placement
        - evpn_options
        - flags
        - gateway
        - gateway_additional_config_cmds
        - gateway_matching
        - gateway_mgmt
        - mxedge
        - mxedge_mgmt
        - mxtunnels
        - ospf_areas
        - paloalto_networks
        - port_mirroring
        - port_usages
        - protect_re
        - radio_config
        - radius_config
        - remote_syslog
        - rtsa
        - status_portal
        - switch
        - switch_matching
        - switch_mgmt
        - tunterm_monitoring
        - tunterm_monitoring_disabled
        - tunterm_multicast_config
        - vrf_instances
        - vrrp_groups
        - vs_instances
      attributes:
        aliases:
          site_id: id
  wlantemplate:
    create:
      path: /api/v1/orgs/{org_id}/templates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          template_id: id      
  wlan:
    create:
      path: /api/v1/orgs/{org_id}/wlans
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - rateset
      attributes:
        aliases:
          wlan_id: id      
