provider:
  name: mistapi
resources:
  # org:
  #   create:
  #     path: /api/v1/orgs
  #     method: POST
  #   read:
  #     path: /api/v1/orgs/{org_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/orgs/{org_id}
  #     method: DELETE
  #   update:
  #     path: /api/v1/orgs/{org_id}
  #     method: PUT      
  #   schema:
  #     ignores:
  #       - created_time
  #       - modified_time
  #     attributes:
  #       aliases:
  #         org_id: id
  # site:
  #   create:
  #     path: /api/v1/orgs/{org_id}/sites
  #     method: POST
  #   read:
  #     path: /api/v1/sites/{site_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/sites/{site_id}
  #     method: DELETE
  #   update:
  #     path: /api/v1/sites/{site_id}
  #     method: PUT      
  #   schema:
  #     attributes:
  #       aliases:
  #         site_id: id
  #     ignores:
  #       - created_time
  #       - modified_time
  # sitegroup:
  #   create:
  #     path: /api/v1/orgs/{org_id}/sitegroups
  #     method: POST
  #   read:
  #     path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
  #     method: DELETE
  #   update:
  #     path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
  #     method: PUT      
  #   schema:
  #     ignores:
  #       - created_time
  #       - modified_time
  #       - site_ids
  #     attributes:
  #       aliases:
  #         sitegroup_id: id
  networktemplate:
    create:
      path: /api/v1/orgs/{org_id}/networktemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - acl_tags
        - import_org_networks
        - snmp_config
        - switch_matching
        - switch_mgmt
        - extra_routes
        - extra_routes6
      attributes:
        aliases:
          networktemplate_id: id
        
