provider:
  name: mistapi
data_sources:
  countries:
    read:
      path: /api/v1/const/countries
      method: GET
  # device_ap_stats:
  #   read: 
  #     path: /api/v1/orgs/{org_id}/stats/devices
  #     method: GET
  #   schema:
  #     ignores:
  #       - evpn_unused
  #       - evpntopo_id
  #       - radio_config
  #       - fields
  #       - limit
  #       - page
  #       - type
  # device_switch_stats:
  #   read: 
  #     path: /api/v1/orgs/{org_id}/stats/devices
  #     method: GET
  #   schema:
  #     ignores:
  #     - fields
  #     - limit
  #     - page
  #     - type
  device_gateway_stats:
    read: 
      path: /api/v1/orgs/{org_id}/stats/devices
      method: GET
    schema:
      ignores:
        - evpn_unused
        - evpntopo_id
        - fields
        - limit
        - page
        - type
        - module_stat.fpc_idx
        - module2_stat.fpc_idx
resources:
  org:
    create:
      path: /api/v1/orgs
      method: POST
    read:
      path: /api/v1/orgs/{org_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          org_id: id
  site:
    create:
      path: /api/v1/orgs/{org_id}/sites
      method: POST
    read:
      path: /api/v1/sites/{site_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          site_id: id
      ignores:
        - created_time
        - modified_time
  org_sitegroup:
    create:
      path: /api/v1/orgs/{org_id}/sitegroups
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - site_ids
      attributes:
        aliases:
          sitegroup_id: id
  org_networktemplate:
    create:
      path: /api/v1/orgs/{org_id}/networktemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networktemplates/{networktemplate_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - import_org_networks
        - switch_matching.rules.switch_mgmt
      attributes:
        aliases:
          networktemplate_id: id
  org_service:
    create:
      path: /api/v1/orgs/{org_id}/services
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          service_id: id
  org_network:
    create:
      path: /api/v1/orgs/{org_id}/networks
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          network_id: id
  org_gatewaytemplate:
    create:
      path: /api/v1/orgs/{org_id}/gatewaytemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/gatewaytemplates/{gatewaytemplate_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
        - gateway_matching
        - idp_profiles.created_time
        - idp_profiles.modified_time
        - idp_profiles.id
        - networks.created_time
        - networks.modified_time
        - networks.id
        - networks.org_id
      attributes:
        aliases:
          gatewaytemplate_id: id
  org_nactag:
    create:
      path: /api/v1/orgs/{org_id}/nactags
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/nactags/{nactag_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          nactag_id: id
      ignores:
        - created_time
        - modified_time
  org_nacrule:
    create:
      path: /api/v1/orgs/{org_id}/nacrules
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/nacrules/{nacrule_id}
      method: PUT      
    schema:
      attributes:
        aliases:
          nacrule_id: id
      ignores:
        - created_time
        - modified_time
  org_rftemplate:
    create:
      path: /api/v1/orgs/{org_id}/rftemplates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/rftemplates/{rftemplate_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          rftemplate_id: id
  site_setting:
    create:
      path: /api/v1/sites/{site_id}/setting
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/setting
      method: GET
    update:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    delete:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    schema:
      ignores:
        # temp fix
        - analytic
        - srx_app
        - vna
        - wan_vna
        - wired_van
        ##
        - created_time
        - modified_time
        - id
        - for_site
        - flags
        - status_portal
        - rtsa
        ## AP
        - ap_matching
        - ap_port_config
        - auto_placement
        - radio_config
        ## MX EDGE
        - mxedge
        - mxedge_mgmt
        - mxtunnels
        - tunterm_monitoring
        - tunterm_monitoring_disabled
        - tunterm_multicast_config
        # OTHERS
        - evpn_options
        - gateway
        - gateway_matching
        - gateway_mgmt
        - ospf_areas
        - paloalto_networks
        - switch
        - vrrp_groups
        ### SWITCH TPL
        - acl_policies
        - acl_tags
        - additional_config_cmds
        - dhcp_snooping
        - dns_servers
        - dns_suffix
        - extra_routes
        - extra_routes6
        - id
        - mist_nac
        - name
        - networks
        - ntp_servers
        - port_mirroring
        - port_usages
        - radius_config
        - remote_syslog
        - snmp_config
        - switch_matching
        - switch_mgmt
        - vrf_config
        - vrf_instances    
        ## GATEWAY TPL
        - gateway_additional_config_cmds
        - bgp_config
        - dhcpd_config
        - dns_override
        - dns_servers
        - dns_suffix
        - id
        - idp_profiles
        - ip_configs
        - name
        - networks
        - ntp_override
        - ntp_servers
        - path_preferences
        - port_config
        - router_id
        - routing_policies
        - service_policies
        - tunnel_configs
        - tunnel_provider_options
        - type         
      attributes:
        aliases:
          site_id: id
  site_networktemplate:
    create:
      path: /api/v1/sites/{site_id}/setting
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/setting
      method: GET
    update:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    delete:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    schema:
      ignores:
      ## temp fix
        - vrb_config
      ##
        - switch_matching.rules.switch_mgmt
        ###
        - analytic
        - ap_matching
        - ap_port_config
        - ap_updown_threshold
        - auto_placement
        - auto_upgrade
        - blacklist_url
        - ble_config
        - config_auto_revert
        - config_push_policy
        - created_time
        - critical_url_monitoring
        - device_updown_threshold
        - disabled_system_defined_port_usages
        - engagement
        - evpn_options
        - flags
        - for_site
        - gateway
        - gateway_additional_config_cmds
        - gateway_mgmt
        - gateway_updown_threshold
        - led
        - modified_time
        - mxedge
        - mxedge_mgmt
        - mxtunnels
        - occupancy
        - org_id
        - ospf_areas
        - paloalto_networks
        - persist_config_on_device
        - proxy
        - radio_config
        - report_gatt
        - rogue
        - rtsa
        - simple_alert
        - site_id
        - skyatp
        - srx_app
        - ssh_keys
        - ssr
        - status_portal
        - switch
        - switch_updown_threshold
        - synthetic_test
        - track_anonymous_devices
        - tunterm_monitoring
        - tunterm_monitoring_disabled
        - tunterm_multicast_config
        - vars
        - vna
        - vrrp_groups
        - wan_vna
        - watched_station_url
        - whitelist_url
        - wids
        - wifi
        - wired_vna
        - zone_occupancy_alert
      attributes:
        aliases:
          site_id: id
  org_wlantemplate:
    create:
      path: /api/v1/orgs/{org_id}/templates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          template_id: id      
  org_wlan:
    create:
      path: /api/v1/orgs/{org_id}/wlans
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/wlans/{wlan_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - mxtunnel_id
        - rateset
        - band
      attributes:
        aliases:
          wlan_id: id      
  site_wlan:
    create:
      path: /api/v1/sites/{site_id}/wlans
      method: POST
    read:
      path: /api/v1/sites/{site_id}/wlans/{wlan_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/wlans/{wlan_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}/wlans/{wlan_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - template_id
        - mxtunnel_id
        - rateset
        - band
      attributes:
        aliases:
          wlan_id: id      
  org_wxrule:
    create:
      path: /api/v1/orgs/{org_id}/wxrules
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/wxrules/{wxrule_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/wxrules/{wxrule_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/wxrules/{wxrule_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          wxrule_id: id      
  org_wxtag:
    create:
      path: /api/v1/orgs/{org_id}/wxtags
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          wxtag_id: id     
  site_wxrule:
    create:
      path: /api/v1/sites/{site_id}/wxrules
      method: POST
    read:
      path: /api/v1/sites/{site_id}/wxrules/{wxrule_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/wxrules/{wxrule_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}/wxrules/{wxrule_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          wxrule_id: id      
  site_wxtag:
    create:
      path: /api/v1/sites/{site_id}/wxtags
      method: POST
    read:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          wxtag_id: id     
  # device_ap:
  #   create:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   read:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   update:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT      
  #   schema:
  #     ignores:
  #       - created_time
  #       - modified_time
  #       - for_site
  #       - id
  #       - iot_config
  #       - port_config
  # device_switch:
  #   create:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   read:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   update:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT      
  #   schema:
  #     ignores:
  #       - created_time
  #       - modified_time
  #       - for_site
  #       - id
  # device_gateway:
  #   create:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   read:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: GET
  #   delete:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT
  #   update:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}
  #     method: PUT      
  #   schema:
  #     ignores:
  #       - created_time
  #       - modified_time
  #       - for_site
  #       - id
  # org_inventory:
  #   create:
  #     path: /api/v1/orgs/{org_id}/inventory
  #     method: POST
  #   read:
  #     path: /api/v1/orgs/{org_id}/inventory
  #     method: GET
  #   delete:
  #     path: /api/v1/orgs/{org_id}/inventory
  #     method: PUT
  #   update:
  #     path: /api/v1/orgs/{org_id}/inventory
  #     method: PUT        
  # device_gateway_cluster:
  #   create:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}/ha
  #     method: POST
  #   read:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}/ha
  #     method: GET
  #   delete:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}/ha
  #     method: DELETE
  #   update:
  #     path: /api/v1/sites/{site_id}/devices/{device_id}/ha
  #     method: PUT
