provider:
  name: mistapi
resources:
  org_mx_tunnel:
    create:
      path: /api/v1/orgs/{org_id}/mxtunnels
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/mxtunnels/{mxtunnel_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/mxtunnels/{mxtunnel_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/mxtunnels/{mxtunnel_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - site_id
      attributes:
        aliases:
          mxtunnel_id: id     
