provider:
  name: mistapi
data_sources:
  const_alarms:
    read:
      path: /api/v1/const/alarm_defs
      method: GET 
    schema:
      ignores:
      - example
      - fields
      - marvis_suggestion_category