provider:
  name: mistapi
resources:
  org_network:
    create:
      path: /api/v1/orgs/{org_id}/networks
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/networks/{network_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          network_id: id