/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the NetworkTemplateVrfConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkTemplateVrfConfig{}

// NetworkTemplateVrfConfig struct for NetworkTemplateVrfConfig
type NetworkTemplateVrfConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NetworkTemplateVrfConfig NetworkTemplateVrfConfig

// NewNetworkTemplateVrfConfig instantiates a new NetworkTemplateVrfConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkTemplateVrfConfig() *NetworkTemplateVrfConfig {
	this := NetworkTemplateVrfConfig{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewNetworkTemplateVrfConfigWithDefaults instantiates a new NetworkTemplateVrfConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkTemplateVrfConfigWithDefaults() *NetworkTemplateVrfConfig {
	this := NetworkTemplateVrfConfig{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NetworkTemplateVrfConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkTemplateVrfConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NetworkTemplateVrfConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NetworkTemplateVrfConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o NetworkTemplateVrfConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkTemplateVrfConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkTemplateVrfConfig) UnmarshalJSON(data []byte) (err error) {
	varNetworkTemplateVrfConfig := _NetworkTemplateVrfConfig{}

	err = json.Unmarshal(data, &varNetworkTemplateVrfConfig)

	if err != nil {
		return err
	}

	*o = NetworkTemplateVrfConfig(varNetworkTemplateVrfConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkTemplateVrfConfig struct {
	value *NetworkTemplateVrfConfig
	isSet bool
}

func (v NullableNetworkTemplateVrfConfig) Get() *NetworkTemplateVrfConfig {
	return v.value
}

func (v *NullableNetworkTemplateVrfConfig) Set(val *NetworkTemplateVrfConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkTemplateVrfConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkTemplateVrfConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkTemplateVrfConfig(val *NetworkTemplateVrfConfig) *NullableNetworkTemplateVrfConfig {
	return &NullableNetworkTemplateVrfConfig{value: val, isSet: true}
}

func (v NullableNetworkTemplateVrfConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkTemplateVrfConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


