/*
Mist API

> Version: **2406.1.7** > > Date: **June 27, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.7
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the SleImpactSummaryAp1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SleImpactSummaryAp1{}

// SleImpactSummaryAp1 struct for SleImpactSummaryAp1
type SleImpactSummaryAp1 struct {
	ApMac string `json:"ap_mac"`
	Degraded float32 `json:"degraded"`
	Duration float32 `json:"duration"`
	Name string `json:"name"`
	Total float32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _SleImpactSummaryAp1 SleImpactSummaryAp1

// NewSleImpactSummaryAp1 instantiates a new SleImpactSummaryAp1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSleImpactSummaryAp1(apMac string, degraded float32, duration float32, name string, total float32) *SleImpactSummaryAp1 {
	this := SleImpactSummaryAp1{}
	this.ApMac = apMac
	this.Degraded = degraded
	this.Duration = duration
	this.Name = name
	this.Total = total
	return &this
}

// NewSleImpactSummaryAp1WithDefaults instantiates a new SleImpactSummaryAp1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSleImpactSummaryAp1WithDefaults() *SleImpactSummaryAp1 {
	this := SleImpactSummaryAp1{}
	return &this
}

// GetApMac returns the ApMac field value
func (o *SleImpactSummaryAp1) GetApMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApMac
}

// GetApMacOk returns a tuple with the ApMac field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryAp1) GetApMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApMac, true
}

// SetApMac sets field value
func (o *SleImpactSummaryAp1) SetApMac(v string) {
	o.ApMac = v
}

// GetDegraded returns the Degraded field value
func (o *SleImpactSummaryAp1) GetDegraded() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Degraded
}

// GetDegradedOk returns a tuple with the Degraded field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryAp1) GetDegradedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Degraded, true
}

// SetDegraded sets field value
func (o *SleImpactSummaryAp1) SetDegraded(v float32) {
	o.Degraded = v
}

// GetDuration returns the Duration field value
func (o *SleImpactSummaryAp1) GetDuration() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryAp1) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *SleImpactSummaryAp1) SetDuration(v float32) {
	o.Duration = v
}

// GetName returns the Name field value
func (o *SleImpactSummaryAp1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryAp1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SleImpactSummaryAp1) SetName(v string) {
	o.Name = v
}

// GetTotal returns the Total field value
func (o *SleImpactSummaryAp1) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryAp1) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *SleImpactSummaryAp1) SetTotal(v float32) {
	o.Total = v
}

func (o SleImpactSummaryAp1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SleImpactSummaryAp1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ap_mac"] = o.ApMac
	toSerialize["degraded"] = o.Degraded
	toSerialize["duration"] = o.Duration
	toSerialize["name"] = o.Name
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SleImpactSummaryAp1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ap_mac",
		"degraded",
		"duration",
		"name",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSleImpactSummaryAp1 := _SleImpactSummaryAp1{}

	err = json.Unmarshal(data, &varSleImpactSummaryAp1)

	if err != nil {
		return err
	}

	*o = SleImpactSummaryAp1(varSleImpactSummaryAp1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ap_mac")
		delete(additionalProperties, "degraded")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "name")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSleImpactSummaryAp1 struct {
	value *SleImpactSummaryAp1
	isSet bool
}

func (v NullableSleImpactSummaryAp1) Get() *SleImpactSummaryAp1 {
	return v.value
}

func (v *NullableSleImpactSummaryAp1) Set(val *SleImpactSummaryAp1) {
	v.value = val
	v.isSet = true
}

func (v NullableSleImpactSummaryAp1) IsSet() bool {
	return v.isSet
}

func (v *NullableSleImpactSummaryAp1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSleImpactSummaryAp1(val *SleImpactSummaryAp1) *NullableSleImpactSummaryAp1 {
	return &NullableSleImpactSummaryAp1{value: val, isSet: true}
}

func (v NullableSleImpactSummaryAp1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSleImpactSummaryAp1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


