/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// GatewayTemplateTunnelEncAlgo the model 'GatewayTemplateTunnelEncAlgo'
type GatewayTemplateTunnelEncAlgo string

// List of gateway_template_tunnel_enc_algo
const (
	GATEWAYTEMPLATETUNNELENCALGO_AES256 GatewayTemplateTunnelEncAlgo = "aes256"
	GATEWAYTEMPLATETUNNELENCALGO__3DES GatewayTemplateTunnelEncAlgo = "3des"
	GATEWAYTEMPLATETUNNELENCALGO_AES128 GatewayTemplateTunnelEncAlgo = "aes128"
	GATEWAYTEMPLATETUNNELENCALGO_AES_GCM256 GatewayTemplateTunnelEncAlgo = "aes_gcm256"
	GATEWAYTEMPLATETUNNELENCALGO_AES_GCM128 GatewayTemplateTunnelEncAlgo = "aes_gcm128"
)

// All allowed values of GatewayTemplateTunnelEncAlgo enum
var AllowedGatewayTemplateTunnelEncAlgoEnumValues = []GatewayTemplateTunnelEncAlgo{
	"aes256",
	"3des",
	"aes128",
	"aes_gcm256",
	"aes_gcm128",
}

func (v *GatewayTemplateTunnelEncAlgo) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayTemplateTunnelEncAlgo(value)
	for _, existing := range AllowedGatewayTemplateTunnelEncAlgoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayTemplateTunnelEncAlgo", value)
}

// NewGatewayTemplateTunnelEncAlgoFromValue returns a pointer to a valid GatewayTemplateTunnelEncAlgo
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayTemplateTunnelEncAlgoFromValue(v string) (*GatewayTemplateTunnelEncAlgo, error) {
	ev := GatewayTemplateTunnelEncAlgo(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayTemplateTunnelEncAlgo: valid values are %v", v, AllowedGatewayTemplateTunnelEncAlgoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayTemplateTunnelEncAlgo) IsValid() bool {
	for _, existing := range AllowedGatewayTemplateTunnelEncAlgoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to gateway_template_tunnel_enc_algo value
func (v GatewayTemplateTunnelEncAlgo) Ptr() *GatewayTemplateTunnelEncAlgo {
	return &v
}

type NullableGatewayTemplateTunnelEncAlgo struct {
	value *GatewayTemplateTunnelEncAlgo
	isSet bool
}

func (v NullableGatewayTemplateTunnelEncAlgo) Get() *GatewayTemplateTunnelEncAlgo {
	return v.value
}

func (v *NullableGatewayTemplateTunnelEncAlgo) Set(val *GatewayTemplateTunnelEncAlgo) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTemplateTunnelEncAlgo) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTemplateTunnelEncAlgo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTemplateTunnelEncAlgo(val *GatewayTemplateTunnelEncAlgo) *NullableGatewayTemplateTunnelEncAlgo {
	return &NullableGatewayTemplateTunnelEncAlgo{value: val, isSet: true}
}

func (v NullableGatewayTemplateTunnelEncAlgo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTemplateTunnelEncAlgo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

