/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the GatewayNetworksValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayNetworksValue{}

// GatewayNetworksValue struct for GatewayNetworksValue
type GatewayNetworksValue struct {
	VlanId *int32 `json:"vlan_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GatewayNetworksValue GatewayNetworksValue

// NewGatewayNetworksValue instantiates a new GatewayNetworksValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayNetworksValue() *GatewayNetworksValue {
	this := GatewayNetworksValue{}
	return &this
}

// NewGatewayNetworksValueWithDefaults instantiates a new GatewayNetworksValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayNetworksValueWithDefaults() *GatewayNetworksValue {
	this := GatewayNetworksValue{}
	return &this
}

// GetVlanId returns the VlanId field value if set, zero value otherwise.
func (o *GatewayNetworksValue) GetVlanId() int32 {
	if o == nil || IsNil(o.VlanId) {
		var ret int32
		return ret
	}
	return *o.VlanId
}

// GetVlanIdOk returns a tuple with the VlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworksValue) GetVlanIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanId) {
		return nil, false
	}
	return o.VlanId, true
}

// HasVlanId returns a boolean if a field has been set.
func (o *GatewayNetworksValue) HasVlanId() bool {
	if o != nil && !IsNil(o.VlanId) {
		return true
	}

	return false
}

// SetVlanId gets a reference to the given int32 and assigns it to the VlanId field.
func (o *GatewayNetworksValue) SetVlanId(v int32) {
	o.VlanId = &v
}

func (o GatewayNetworksValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayNetworksValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VlanId) {
		toSerialize["vlan_id"] = o.VlanId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GatewayNetworksValue) UnmarshalJSON(data []byte) (err error) {
	varGatewayNetworksValue := _GatewayNetworksValue{}

	err = json.Unmarshal(data, &varGatewayNetworksValue)

	if err != nil {
		return err
	}

	*o = GatewayNetworksValue(varGatewayNetworksValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vlan_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGatewayNetworksValue struct {
	value *GatewayNetworksValue
	isSet bool
}

func (v NullableGatewayNetworksValue) Get() *GatewayNetworksValue {
	return v.value
}

func (v *NullableGatewayNetworksValue) Set(val *GatewayNetworksValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayNetworksValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayNetworksValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayNetworksValue(val *GatewayNetworksValue) *NullableGatewayNetworksValue {
	return &NullableGatewayNetworksValue{value: val, isSet: true}
}

func (v NullableGatewayNetworksValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayNetworksValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


