/*
Mist API

> Version: **2406.1.9** > > Date: **June 28, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.9
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookLocation{}

// WebhookLocation location webhook sample
type WebhookLocation struct {
	// list of events
	Events []WebhookLocationEvent `json:"events"`
	// topic subscribed to
	Topic string `json:"topic"`
	AdditionalProperties map[string]interface{}
}

type _WebhookLocation WebhookLocation

// NewWebhookLocation instantiates a new WebhookLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookLocation(events []WebhookLocationEvent, topic string) *WebhookLocation {
	this := WebhookLocation{}
	this.Events = events
	this.Topic = topic
	return &this
}

// NewWebhookLocationWithDefaults instantiates a new WebhookLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookLocationWithDefaults() *WebhookLocation {
	this := WebhookLocation{}
	var topic string = "location"
	this.Topic = topic
	return &this
}

// GetEvents returns the Events field value
func (o *WebhookLocation) GetEvents() []WebhookLocationEvent {
	if o == nil {
		var ret []WebhookLocationEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookLocation) GetEventsOk() ([]WebhookLocationEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookLocation) SetEvents(v []WebhookLocationEvent) {
	o.Events = v
}

// GetTopic returns the Topic field value
func (o *WebhookLocation) GetTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topic
}

// GetTopicOk returns a tuple with the Topic field value
// and a boolean to check if the value has been set.
func (o *WebhookLocation) GetTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topic, true
}

// SetTopic sets field value
func (o *WebhookLocation) SetTopic(v string) {
	o.Topic = v
}

func (o WebhookLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["topic"] = o.Topic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"topic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookLocation := _WebhookLocation{}

	err = json.Unmarshal(data, &varWebhookLocation)

	if err != nil {
		return err
	}

	*o = WebhookLocation(varWebhookLocation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookLocation struct {
	value *WebhookLocation
	isSet bool
}

func (v NullableWebhookLocation) Get() *WebhookLocation {
	return v.value
}

func (v *NullableWebhookLocation) Set(val *WebhookLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookLocation(val *WebhookLocation) *NullableWebhookLocation {
	return &NullableWebhookLocation{value: val, isSet: true}
}

func (v NullableWebhookLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


