/*
Mist API

> Version: **2406.1.10** > > Date: **June 29, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.10
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookDiscoveredRawRssi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDiscoveredRawRssi{}

// WebhookDiscoveredRawRssi struct for WebhookDiscoveredRawRssi
type WebhookDiscoveredRawRssi struct {
	Events []WebhookDiscoveredRawRssiEvent `json:"events,omitempty"`
	Topic string `json:"topic"`
	AdditionalProperties map[string]interface{}
}

type _WebhookDiscoveredRawRssi WebhookDiscoveredRawRssi

// NewWebhookDiscoveredRawRssi instantiates a new WebhookDiscoveredRawRssi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDiscoveredRawRssi(topic string) *WebhookDiscoveredRawRssi {
	this := WebhookDiscoveredRawRssi{}
	this.Topic = topic
	return &this
}

// NewWebhookDiscoveredRawRssiWithDefaults instantiates a new WebhookDiscoveredRawRssi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDiscoveredRawRssiWithDefaults() *WebhookDiscoveredRawRssi {
	this := WebhookDiscoveredRawRssi{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *WebhookDiscoveredRawRssi) GetEvents() []WebhookDiscoveredRawRssiEvent {
	if o == nil || IsNil(o.Events) {
		var ret []WebhookDiscoveredRawRssiEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDiscoveredRawRssi) GetEventsOk() ([]WebhookDiscoveredRawRssiEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookDiscoveredRawRssi) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []WebhookDiscoveredRawRssiEvent and assigns it to the Events field.
func (o *WebhookDiscoveredRawRssi) SetEvents(v []WebhookDiscoveredRawRssiEvent) {
	o.Events = v
}

// GetTopic returns the Topic field value
func (o *WebhookDiscoveredRawRssi) GetTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topic
}

// GetTopicOk returns a tuple with the Topic field value
// and a boolean to check if the value has been set.
func (o *WebhookDiscoveredRawRssi) GetTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topic, true
}

// SetTopic sets field value
func (o *WebhookDiscoveredRawRssi) SetTopic(v string) {
	o.Topic = v
}

func (o WebhookDiscoveredRawRssi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDiscoveredRawRssi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	toSerialize["topic"] = o.Topic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookDiscoveredRawRssi) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"topic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookDiscoveredRawRssi := _WebhookDiscoveredRawRssi{}

	err = json.Unmarshal(data, &varWebhookDiscoveredRawRssi)

	if err != nil {
		return err
	}

	*o = WebhookDiscoveredRawRssi(varWebhookDiscoveredRawRssi)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookDiscoveredRawRssi struct {
	value *WebhookDiscoveredRawRssi
	isSet bool
}

func (v NullableWebhookDiscoveredRawRssi) Get() *WebhookDiscoveredRawRssi {
	return v.value
}

func (v *NullableWebhookDiscoveredRawRssi) Set(val *WebhookDiscoveredRawRssi) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDiscoveredRawRssi) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDiscoveredRawRssi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDiscoveredRawRssi(val *WebhookDiscoveredRawRssi) *NullableWebhookDiscoveredRawRssi {
	return &NullableWebhookDiscoveredRawRssi{value: val, isSet: true}
}

func (v NullableWebhookDiscoveredRawRssi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDiscoveredRawRssi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


