/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the SnmpV3ConfigNotifyFilterInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnmpV3ConfigNotifyFilterInner{}

// SnmpV3ConfigNotifyFilterInner struct for SnmpV3ConfigNotifyFilterInner
type SnmpV3ConfigNotifyFilterInner struct {
	Contents []SnmpV3ConfigNotifyFilterInnerContentsInner `json:"contents,omitempty"`
	ProfileName *string `json:"profile_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SnmpV3ConfigNotifyFilterInner SnmpV3ConfigNotifyFilterInner

// NewSnmpV3ConfigNotifyFilterInner instantiates a new SnmpV3ConfigNotifyFilterInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnmpV3ConfigNotifyFilterInner() *SnmpV3ConfigNotifyFilterInner {
	this := SnmpV3ConfigNotifyFilterInner{}
	return &this
}

// NewSnmpV3ConfigNotifyFilterInnerWithDefaults instantiates a new SnmpV3ConfigNotifyFilterInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnmpV3ConfigNotifyFilterInnerWithDefaults() *SnmpV3ConfigNotifyFilterInner {
	this := SnmpV3ConfigNotifyFilterInner{}
	return &this
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *SnmpV3ConfigNotifyFilterInner) GetContents() []SnmpV3ConfigNotifyFilterInnerContentsInner {
	if o == nil || IsNil(o.Contents) {
		var ret []SnmpV3ConfigNotifyFilterInnerContentsInner
		return ret
	}
	return o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnmpV3ConfigNotifyFilterInner) GetContentsOk() ([]SnmpV3ConfigNotifyFilterInnerContentsInner, bool) {
	if o == nil || IsNil(o.Contents) {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *SnmpV3ConfigNotifyFilterInner) HasContents() bool {
	if o != nil && !IsNil(o.Contents) {
		return true
	}

	return false
}

// SetContents gets a reference to the given []SnmpV3ConfigNotifyFilterInnerContentsInner and assigns it to the Contents field.
func (o *SnmpV3ConfigNotifyFilterInner) SetContents(v []SnmpV3ConfigNotifyFilterInnerContentsInner) {
	o.Contents = v
}

// GetProfileName returns the ProfileName field value if set, zero value otherwise.
func (o *SnmpV3ConfigNotifyFilterInner) GetProfileName() string {
	if o == nil || IsNil(o.ProfileName) {
		var ret string
		return ret
	}
	return *o.ProfileName
}

// GetProfileNameOk returns a tuple with the ProfileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnmpV3ConfigNotifyFilterInner) GetProfileNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileName) {
		return nil, false
	}
	return o.ProfileName, true
}

// HasProfileName returns a boolean if a field has been set.
func (o *SnmpV3ConfigNotifyFilterInner) HasProfileName() bool {
	if o != nil && !IsNil(o.ProfileName) {
		return true
	}

	return false
}

// SetProfileName gets a reference to the given string and assigns it to the ProfileName field.
func (o *SnmpV3ConfigNotifyFilterInner) SetProfileName(v string) {
	o.ProfileName = &v
}

func (o SnmpV3ConfigNotifyFilterInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnmpV3ConfigNotifyFilterInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contents) {
		toSerialize["contents"] = o.Contents
	}
	if !IsNil(o.ProfileName) {
		toSerialize["profile_name"] = o.ProfileName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SnmpV3ConfigNotifyFilterInner) UnmarshalJSON(data []byte) (err error) {
	varSnmpV3ConfigNotifyFilterInner := _SnmpV3ConfigNotifyFilterInner{}

	err = json.Unmarshal(data, &varSnmpV3ConfigNotifyFilterInner)

	if err != nil {
		return err
	}

	*o = SnmpV3ConfigNotifyFilterInner(varSnmpV3ConfigNotifyFilterInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contents")
		delete(additionalProperties, "profile_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSnmpV3ConfigNotifyFilterInner struct {
	value *SnmpV3ConfigNotifyFilterInner
	isSet bool
}

func (v NullableSnmpV3ConfigNotifyFilterInner) Get() *SnmpV3ConfigNotifyFilterInner {
	return v.value
}

func (v *NullableSnmpV3ConfigNotifyFilterInner) Set(val *SnmpV3ConfigNotifyFilterInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSnmpV3ConfigNotifyFilterInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSnmpV3ConfigNotifyFilterInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnmpV3ConfigNotifyFilterInner(val *SnmpV3ConfigNotifyFilterInner) *NullableSnmpV3ConfigNotifyFilterInner {
	return &NullableSnmpV3ConfigNotifyFilterInner{value: val, isSet: true}
}

func (v NullableSnmpV3ConfigNotifyFilterInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnmpV3ConfigNotifyFilterInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


