/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the JunosDhcpdConfigFixedBindingsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JunosDhcpdConfigFixedBindingsValue{}

// JunosDhcpdConfigFixedBindingsValue struct for JunosDhcpdConfigFixedBindingsValue
type JunosDhcpdConfigFixedBindingsValue struct {
	Ip *string `json:"ip,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JunosDhcpdConfigFixedBindingsValue JunosDhcpdConfigFixedBindingsValue

// NewJunosDhcpdConfigFixedBindingsValue instantiates a new JunosDhcpdConfigFixedBindingsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJunosDhcpdConfigFixedBindingsValue() *JunosDhcpdConfigFixedBindingsValue {
	this := JunosDhcpdConfigFixedBindingsValue{}
	return &this
}

// NewJunosDhcpdConfigFixedBindingsValueWithDefaults instantiates a new JunosDhcpdConfigFixedBindingsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJunosDhcpdConfigFixedBindingsValueWithDefaults() *JunosDhcpdConfigFixedBindingsValue {
	this := JunosDhcpdConfigFixedBindingsValue{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *JunosDhcpdConfigFixedBindingsValue) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosDhcpdConfigFixedBindingsValue) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *JunosDhcpdConfigFixedBindingsValue) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *JunosDhcpdConfigFixedBindingsValue) SetIp(v string) {
	o.Ip = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *JunosDhcpdConfigFixedBindingsValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JunosDhcpdConfigFixedBindingsValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *JunosDhcpdConfigFixedBindingsValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *JunosDhcpdConfigFixedBindingsValue) SetName(v string) {
	o.Name = &v
}

func (o JunosDhcpdConfigFixedBindingsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JunosDhcpdConfigFixedBindingsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JunosDhcpdConfigFixedBindingsValue) UnmarshalJSON(data []byte) (err error) {
	varJunosDhcpdConfigFixedBindingsValue := _JunosDhcpdConfigFixedBindingsValue{}

	err = json.Unmarshal(data, &varJunosDhcpdConfigFixedBindingsValue)

	if err != nil {
		return err
	}

	*o = JunosDhcpdConfigFixedBindingsValue(varJunosDhcpdConfigFixedBindingsValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJunosDhcpdConfigFixedBindingsValue struct {
	value *JunosDhcpdConfigFixedBindingsValue
	isSet bool
}

func (v NullableJunosDhcpdConfigFixedBindingsValue) Get() *JunosDhcpdConfigFixedBindingsValue {
	return v.value
}

func (v *NullableJunosDhcpdConfigFixedBindingsValue) Set(val *JunosDhcpdConfigFixedBindingsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableJunosDhcpdConfigFixedBindingsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableJunosDhcpdConfigFixedBindingsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJunosDhcpdConfigFixedBindingsValue(val *JunosDhcpdConfigFixedBindingsValue) *NullableJunosDhcpdConfigFixedBindingsValue {
	return &NullableJunosDhcpdConfigFixedBindingsValue{value: val, isSet: true}
}

func (v NullableJunosDhcpdConfigFixedBindingsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJunosDhcpdConfigFixedBindingsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


