/*
Mist API

> Version: **2406.1.9** > > Date: **June 28, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.9
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookAudits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookAudits{}

// WebhookAudits audit webhook sample
type WebhookAudits struct {
	Events []WebhookAuditEvent `json:"events"`
	Topic string `json:"topic"`
	AdditionalProperties map[string]interface{}
}

type _WebhookAudits WebhookAudits

// NewWebhookAudits instantiates a new WebhookAudits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookAudits(events []WebhookAuditEvent, topic string) *WebhookAudits {
	this := WebhookAudits{}
	this.Events = events
	this.Topic = topic
	return &this
}

// NewWebhookAuditsWithDefaults instantiates a new WebhookAudits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookAuditsWithDefaults() *WebhookAudits {
	this := WebhookAudits{}
	var topic string = "audits"
	this.Topic = topic
	return &this
}

// GetEvents returns the Events field value
func (o *WebhookAudits) GetEvents() []WebhookAuditEvent {
	if o == nil {
		var ret []WebhookAuditEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookAudits) GetEventsOk() ([]WebhookAuditEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookAudits) SetEvents(v []WebhookAuditEvent) {
	o.Events = v
}

// GetTopic returns the Topic field value
func (o *WebhookAudits) GetTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topic
}

// GetTopicOk returns a tuple with the Topic field value
// and a boolean to check if the value has been set.
func (o *WebhookAudits) GetTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topic, true
}

// SetTopic sets field value
func (o *WebhookAudits) SetTopic(v string) {
	o.Topic = v
}

func (o WebhookAudits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookAudits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["topic"] = o.Topic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookAudits) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"topic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookAudits := _WebhookAudits{}

	err = json.Unmarshal(data, &varWebhookAudits)

	if err != nil {
		return err
	}

	*o = WebhookAudits(varWebhookAudits)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookAudits struct {
	value *WebhookAudits
	isSet bool
}

func (v NullableWebhookAudits) Get() *WebhookAudits {
	return v.value
}

func (v *NullableWebhookAudits) Set(val *WebhookAudits) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookAudits) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookAudits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookAudits(val *WebhookAudits) *NullableWebhookAudits {
	return &NullableWebhookAudits{value: val, isSet: true}
}

func (v NullableWebhookAudits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookAudits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


