/*
Mist API

> Version: **2406.1.10** > > Date: **June 29, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.10
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookLocationAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookLocationAsset{}

// WebhookLocationAsset Location Asset sample
type WebhookLocationAsset struct {
	// list of events
	Events []WebhookLocationAssetEventsInner `json:"events"`
	// topic subscribed to
	Topic string `json:"topic"`
	AdditionalProperties map[string]interface{}
}

type _WebhookLocationAsset WebhookLocationAsset

// NewWebhookLocationAsset instantiates a new WebhookLocationAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookLocationAsset(events []WebhookLocationAssetEventsInner, topic string) *WebhookLocationAsset {
	this := WebhookLocationAsset{}
	this.Events = events
	this.Topic = topic
	return &this
}

// NewWebhookLocationAssetWithDefaults instantiates a new WebhookLocationAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookLocationAssetWithDefaults() *WebhookLocationAsset {
	this := WebhookLocationAsset{}
	var topic string = "location_asset"
	this.Topic = topic
	return &this
}

// GetEvents returns the Events field value
func (o *WebhookLocationAsset) GetEvents() []WebhookLocationAssetEventsInner {
	if o == nil {
		var ret []WebhookLocationAssetEventsInner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookLocationAsset) GetEventsOk() ([]WebhookLocationAssetEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookLocationAsset) SetEvents(v []WebhookLocationAssetEventsInner) {
	o.Events = v
}

// GetTopic returns the Topic field value
func (o *WebhookLocationAsset) GetTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topic
}

// GetTopicOk returns a tuple with the Topic field value
// and a boolean to check if the value has been set.
func (o *WebhookLocationAsset) GetTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topic, true
}

// SetTopic sets field value
func (o *WebhookLocationAsset) SetTopic(v string) {
	o.Topic = v
}

func (o WebhookLocationAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookLocationAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["topic"] = o.Topic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookLocationAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"topic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookLocationAsset := _WebhookLocationAsset{}

	err = json.Unmarshal(data, &varWebhookLocationAsset)

	if err != nil {
		return err
	}

	*o = WebhookLocationAsset(varWebhookLocationAsset)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookLocationAsset struct {
	value *WebhookLocationAsset
	isSet bool
}

func (v NullableWebhookLocationAsset) Get() *WebhookLocationAsset {
	return v.value
}

func (v *NullableWebhookLocationAsset) Set(val *WebhookLocationAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookLocationAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookLocationAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookLocationAsset(val *WebhookLocationAsset) *NullableWebhookLocationAsset {
	return &NullableWebhookLocationAsset{value: val, isSet: true}
}

func (v NullableWebhookLocationAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookLocationAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


