/*
Mist API

> Version: **2406.1.10** > > Date: **June 29, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.10
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the WebhookClientLatency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookClientLatency{}

// WebhookClientLatency struct for WebhookClientLatency
type WebhookClientLatency struct {
	Events []WebhookClientLatencyEvent `json:"events,omitempty"`
	Topic *string `json:"topic,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebhookClientLatency WebhookClientLatency

// NewWebhookClientLatency instantiates a new WebhookClientLatency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookClientLatency() *WebhookClientLatency {
	this := WebhookClientLatency{}
	return &this
}

// NewWebhookClientLatencyWithDefaults instantiates a new WebhookClientLatency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookClientLatencyWithDefaults() *WebhookClientLatency {
	this := WebhookClientLatency{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *WebhookClientLatency) GetEvents() []WebhookClientLatencyEvent {
	if o == nil || IsNil(o.Events) {
		var ret []WebhookClientLatencyEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookClientLatency) GetEventsOk() ([]WebhookClientLatencyEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookClientLatency) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []WebhookClientLatencyEvent and assigns it to the Events field.
func (o *WebhookClientLatency) SetEvents(v []WebhookClientLatencyEvent) {
	o.Events = v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *WebhookClientLatency) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookClientLatency) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *WebhookClientLatency) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *WebhookClientLatency) SetTopic(v string) {
	o.Topic = &v
}

func (o WebhookClientLatency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookClientLatency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookClientLatency) UnmarshalJSON(data []byte) (err error) {
	varWebhookClientLatency := _WebhookClientLatency{}

	err = json.Unmarshal(data, &varWebhookClientLatency)

	if err != nil {
		return err
	}

	*o = WebhookClientLatency(varWebhookClientLatency)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "topic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookClientLatency struct {
	value *WebhookClientLatency
	isSet bool
}

func (v NullableWebhookClientLatency) Get() *WebhookClientLatency {
	return v.value
}

func (v *NullableWebhookClientLatency) Set(val *WebhookClientLatency) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookClientLatency) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookClientLatency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookClientLatency(val *WebhookClientLatency) *NullableWebhookClientLatency {
	return &NullableWebhookClientLatency{value: val, isSet: true}
}

func (v NullableWebhookClientLatency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookClientLatency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


