/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// RemoteSyslogProtocol the model 'RemoteSyslogProtocol'
type RemoteSyslogProtocol string

// List of remote_syslog_protocol
const (
	REMOTESYSLOGPROTOCOL_UDP RemoteSyslogProtocol = "udp"
	REMOTESYSLOGPROTOCOL_TCP RemoteSyslogProtocol = "tcp"
)

// All allowed values of RemoteSyslogProtocol enum
var AllowedRemoteSyslogProtocolEnumValues = []RemoteSyslogProtocol{
	"udp",
	"tcp",
}

func (v *RemoteSyslogProtocol) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RemoteSyslogProtocol(value)
	for _, existing := range AllowedRemoteSyslogProtocolEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RemoteSyslogProtocol", value)
}

// NewRemoteSyslogProtocolFromValue returns a pointer to a valid RemoteSyslogProtocol
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRemoteSyslogProtocolFromValue(v string) (*RemoteSyslogProtocol, error) {
	ev := RemoteSyslogProtocol(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RemoteSyslogProtocol: valid values are %v", v, AllowedRemoteSyslogProtocolEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RemoteSyslogProtocol) IsValid() bool {
	for _, existing := range AllowedRemoteSyslogProtocolEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to remote_syslog_protocol value
func (v RemoteSyslogProtocol) Ptr() *RemoteSyslogProtocol {
	return &v
}

type NullableRemoteSyslogProtocol struct {
	value *RemoteSyslogProtocol
	isSet bool
}

func (v NullableRemoteSyslogProtocol) Get() *RemoteSyslogProtocol {
	return v.value
}

func (v *NullableRemoteSyslogProtocol) Set(val *RemoteSyslogProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteSyslogProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteSyslogProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteSyslogProtocol(val *RemoteSyslogProtocol) *NullableRemoteSyslogProtocol {
	return &NullableRemoteSyslogProtocol{value: val, isSet: true}
}

func (v NullableRemoteSyslogProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteSyslogProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

