/*
Mist API

> Version: **2406.1.3** > > Date: **June 26, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location_services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2406.1.3
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
	"fmt"
)

// checks if the SleImpactSummaryDeviceType1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SleImpactSummaryDeviceType1{}

// SleImpactSummaryDeviceType1 struct for SleImpactSummaryDeviceType1
type SleImpactSummaryDeviceType1 struct {
	Degraded float32 `json:"degraded"`
	DeviceType string `json:"device_type"`
	Duration float32 `json:"duration"`
	Name string `json:"name"`
	Total float32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _SleImpactSummaryDeviceType1 SleImpactSummaryDeviceType1

// NewSleImpactSummaryDeviceType1 instantiates a new SleImpactSummaryDeviceType1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSleImpactSummaryDeviceType1(degraded float32, deviceType string, duration float32, name string, total float32) *SleImpactSummaryDeviceType1 {
	this := SleImpactSummaryDeviceType1{}
	this.Degraded = degraded
	this.DeviceType = deviceType
	this.Duration = duration
	this.Name = name
	this.Total = total
	return &this
}

// NewSleImpactSummaryDeviceType1WithDefaults instantiates a new SleImpactSummaryDeviceType1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSleImpactSummaryDeviceType1WithDefaults() *SleImpactSummaryDeviceType1 {
	this := SleImpactSummaryDeviceType1{}
	return &this
}

// GetDegraded returns the Degraded field value
func (o *SleImpactSummaryDeviceType1) GetDegraded() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Degraded
}

// GetDegradedOk returns a tuple with the Degraded field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryDeviceType1) GetDegradedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Degraded, true
}

// SetDegraded sets field value
func (o *SleImpactSummaryDeviceType1) SetDegraded(v float32) {
	o.Degraded = v
}

// GetDeviceType returns the DeviceType field value
func (o *SleImpactSummaryDeviceType1) GetDeviceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryDeviceType1) GetDeviceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceType, true
}

// SetDeviceType sets field value
func (o *SleImpactSummaryDeviceType1) SetDeviceType(v string) {
	o.DeviceType = v
}

// GetDuration returns the Duration field value
func (o *SleImpactSummaryDeviceType1) GetDuration() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryDeviceType1) GetDurationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *SleImpactSummaryDeviceType1) SetDuration(v float32) {
	o.Duration = v
}

// GetName returns the Name field value
func (o *SleImpactSummaryDeviceType1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryDeviceType1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SleImpactSummaryDeviceType1) SetName(v string) {
	o.Name = v
}

// GetTotal returns the Total field value
func (o *SleImpactSummaryDeviceType1) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *SleImpactSummaryDeviceType1) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *SleImpactSummaryDeviceType1) SetTotal(v float32) {
	o.Total = v
}

func (o SleImpactSummaryDeviceType1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SleImpactSummaryDeviceType1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["degraded"] = o.Degraded
	toSerialize["device_type"] = o.DeviceType
	toSerialize["duration"] = o.Duration
	toSerialize["name"] = o.Name
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SleImpactSummaryDeviceType1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"degraded",
		"device_type",
		"duration",
		"name",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSleImpactSummaryDeviceType1 := _SleImpactSummaryDeviceType1{}

	err = json.Unmarshal(data, &varSleImpactSummaryDeviceType1)

	if err != nil {
		return err
	}

	*o = SleImpactSummaryDeviceType1(varSleImpactSummaryDeviceType1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "degraded")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "name")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSleImpactSummaryDeviceType1 struct {
	value *SleImpactSummaryDeviceType1
	isSet bool
}

func (v NullableSleImpactSummaryDeviceType1) Get() *SleImpactSummaryDeviceType1 {
	return v.value
}

func (v *NullableSleImpactSummaryDeviceType1) Set(val *SleImpactSummaryDeviceType1) {
	v.value = val
	v.isSet = true
}

func (v NullableSleImpactSummaryDeviceType1) IsSet() bool {
	return v.isSet
}

func (v *NullableSleImpactSummaryDeviceType1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSleImpactSummaryDeviceType1(val *SleImpactSummaryDeviceType1) *NullableSleImpactSummaryDeviceType1 {
	return &NullableSleImpactSummaryDeviceType1{value: val, isSet: true}
}

func (v NullableSleImpactSummaryDeviceType1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSleImpactSummaryDeviceType1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


