/*
Mist API

> Version: **2405.1.6** > > Date: **June 6, 2024**  ---  ### Additional Documentation * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html) * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html) * [Mist Product Updates](https://www.mist.com/documentation/category/product-updates/)  ---  ### Helpful Resources * [API Sandbox and Exercises](https://api-class.mist.com/) * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace) * [API Demo Apps](https://apps.mist-lab.fr/) * [Juniper Blog](https://blogs.juniper.net/)  --- 

API version: 2405.1.6
Contact: tmunzer@juniper.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistsdkgo

import (
	"encoding/json"
)

// checks if the SwitchPortUsages type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwitchPortUsages{}

// SwitchPortUsages Property key is the port profile name
type SwitchPortUsages struct {
	Dynamic *DynamicPortUsage `json:"dynamic,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SwitchPortUsages SwitchPortUsages

// NewSwitchPortUsages instantiates a new SwitchPortUsages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitchPortUsages() *SwitchPortUsages {
	this := SwitchPortUsages{}
	return &this
}

// NewSwitchPortUsagesWithDefaults instantiates a new SwitchPortUsages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchPortUsagesWithDefaults() *SwitchPortUsages {
	this := SwitchPortUsages{}
	return &this
}

// GetDynamic returns the Dynamic field value if set, zero value otherwise.
func (o *SwitchPortUsages) GetDynamic() DynamicPortUsage {
	if o == nil || IsNil(o.Dynamic) {
		var ret DynamicPortUsage
		return ret
	}
	return *o.Dynamic
}

// GetDynamicOk returns a tuple with the Dynamic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortUsages) GetDynamicOk() (*DynamicPortUsage, bool) {
	if o == nil || IsNil(o.Dynamic) {
		return nil, false
	}
	return o.Dynamic, true
}

// HasDynamic returns a boolean if a field has been set.
func (o *SwitchPortUsages) HasDynamic() bool {
	if o != nil && !IsNil(o.Dynamic) {
		return true
	}

	return false
}

// SetDynamic gets a reference to the given DynamicPortUsage and assigns it to the Dynamic field.
func (o *SwitchPortUsages) SetDynamic(v DynamicPortUsage) {
	o.Dynamic = &v
}

func (o SwitchPortUsages) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwitchPortUsages) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dynamic) {
		toSerialize["dynamic"] = o.Dynamic
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SwitchPortUsages) UnmarshalJSON(data []byte) (err error) {
	varSwitchPortUsages := _SwitchPortUsages{}

	err = json.Unmarshal(data, &varSwitchPortUsages)

	if err != nil {
		return err
	}

	*o = SwitchPortUsages(varSwitchPortUsages)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dynamic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSwitchPortUsages struct {
	value *SwitchPortUsages
	isSet bool
}

func (v NullableSwitchPortUsages) Get() *SwitchPortUsages {
	return v.value
}

func (v *NullableSwitchPortUsages) Set(val *SwitchPortUsages) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchPortUsages) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchPortUsages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchPortUsages(val *SwitchPortUsages) *NullableSwitchPortUsages {
	return &NullableSwitchPortUsages{value: val, isSet: true}
}

func (v NullableSwitchPortUsages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchPortUsages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


