provider:
  name: mistapi
resources:
  org_wlantemplate:
    create:
      path: /api/v1/orgs/{org_id}/templates
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/templates/{template_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          template_id: id   