provider:
  name: mistapi
resources:
  device_switch:
    create:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    update:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - id
        - switch_mgmt.radius
        - deviceprofile_id