provider:
  name: mistapi
resources:
  org_vpn:
    create:
      path: /api/v1/orgs/{org_id}/vpns
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/vpns/{vpn_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/vpns/{vpn_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/vpns/{vpn_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
      attributes:
        aliases:
          vpn_id: id     
