provider:
  name: mistapi
resources:
  site_setting:
    create:
      path: /api/v1/sites/{site_id}/setting
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/setting
      method: GET
    update:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    delete:
      path: /api/v1/sites/{site_id}/setting
      method: PUT      
    schema:
      ignores:
        - org_id
        ##
        - created_time
        - modified_time
        - id
        - for_site
        - flags
        - status_portal
        ## AP
        - ap_matching
        - ap_port_config
        - auto_placement
        - radio_config
        ## MX EDGE
        - mxedge
        - mxedge_mgmt
        - mxtunnels
        - tunterm_monitoring
        - tunterm_monitoring_disabled
        - tunterm_multicast_config
        # OTHERS
        - evpn_options
        - gateway
        - gateway_matching
        - ospf_areas
        - paloalto_networks
        - switch
        - vrrp_groups
        ### SWITCH TPL
        - acl_policies
        - acl_tags
        - additional_config_cmds
        - dhcp_snooping
        - dns_servers
        - dns_suffix
        - extra_routes
        - extra_routes6
        - id
        - mist_nac
        - name
        - networks
        - ntp_servers
        - port_mirroring
        - port_usages
        - radius_config
        - remote_syslog
        - snmp_config
        - switch_matching
        - switch_mgmt
        - vrf_config
        - vrf_instances    
        ## GATEWAY TPL
        - gateway_additional_config_cmds
        - bgp_config
        - dhcpd_config
        - dns_override
        - dns_servers
        - dns_suffix
        - id
        - idp_profiles
        - ip_configs
        - name
        - networks
        - ntp_override
        - ntp_servers
        - path_preferences
        - port_config
        - router_id
        - routing_policies
        - service_policies
        - tunnel_configs
        - tunnel_provider_options
        - type         
      attributes:
        aliases:
          site_id: id
