provider:
  name: mistapi
resources:
  org_service:
    create:
      path: /api/v1/orgs/{org_id}/services
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/services/{service_id}
      method: PUT
    schema:
      ignores:
        - created_time
        - modified_time
      attributes:
        aliases:
          service_id: id