provider:
  name: mistapi
data_sources:
  org_vpns:
    read:
      path: /api/v1/orgs/{org_id}/vpns
      method: GET 
    schema:
      ignores:
      - for_site
      - limit
      - page
      - type