provider:
  name: mistapi
resources:
  org_sso_role:
    create:
      path: /api/v1/orgs/{org_id}/ssoroles
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/ssoroles/{ssorole_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/ssoroles/{ssorole_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/ssoroles/{ssorole_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - msp_id
        - site_id
        - for_site
        - privileges.org_id
      attributes:
        aliases:
          ssorole_id: id