provider:
  name: mistapi
resources:
  device_gateway:
    create:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    update:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - id
        - deviceprofile_id
        - idp_profiles.created_time
        - idp_profiles.modified_time
        - networks.created_time
        - networks.modified_time
        - networks.id
        - networks.org_id