provider:
  name: mistapi
resources:
  org_wxtag:
    create:
      path: /api/v1/orgs/{org_id}/wxtags
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/wxtags/{wxtag_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - site_id
        - last_ips
        - resource_mac
        - services
        - subnet
      attributes:
        aliases:
          wxtag_id: id         
  site_wxtag:
    create:
      path: /api/v1/sites/{site_id}/wxtags
      method: POST
    read:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}/wxtags/{wxtag_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - last_ips
        - resource_mac
        - services
        - subnet
        - org_id
      attributes:
        aliases:
          wxtag_id: id   