package resource_org_wlan

import (
	"context"
	mistsdkgo "terraform-provider-mist/github.com/tmunzer/mist-sdk-go"
	mist_transform "terraform-provider-mist/internal/commons/utils"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func SdkToTerraform(ctx context.Context, data *mistsdkgo.Wlan) (OrgWlanModel, diag.Diagnostics) {
	var state OrgWlanModel
	var diags diag.Diagnostics

	state.Id = types.StringValue(data.GetId())
	state.SiteId = types.StringValue(data.GetSiteId())
	state.OrgId = types.StringValue(data.GetOrgId())
	state.TemplateId = types.StringValue(data.GetTemplateId())
	state.Ssid = types.StringValue(data.GetSsid())

	state.AcctImmediateUpdate = types.BoolValue(data.GetAcctImmediateUpdate())
	state.AcctInterimInterval = types.Int64Value(int64(data.GetAcctInterimInterval()))
	state.AcctServers = radiusServersAcctSdkToTerraform(ctx, &diags, data.GetAcctServers())
	state.Airwatch = airwatchSdkToTerraform(ctx, &diags, data.GetAirwatch())
	state.AllowIpv6Ndp = types.BoolValue(data.GetAllowIpv6Ndp())
	state.AllowMdns = types.BoolValue(data.GetAllowMdns())
	state.AllowSsdp = types.BoolValue(data.GetAllowSsdp())
	state.ApIds = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetApIds())
	state.AppLimit = appLimitSdkToTerraform(ctx, &diags, data.GetAppLimit())
	state.AppQos = appQosSdkToTerraform(ctx, &diags, data.GetAppQos())
	state.ApplyTo = types.StringValue(string(data.GetApplyTo()))
	state.ArpFilter = types.BoolValue(data.GetArpFilter())
	state.Auth = authSdkToTerraform(ctx, &diags, data.GetAuth())
	state.AuthServerSelection = types.StringValue(string(data.GetAuthServerSelection()))
	state.AuthServers = radiusServersAuthSdkToTerraform(ctx, &diags, data.GetAuthServers())
	state.AuthServersNasId = types.StringValue(data.GetAuthServersNasId())
	state.AuthServersNasIp = types.StringValue(data.GetAuthServersNasIp())
	state.AuthServersRetries = types.Int64Value(int64(data.GetAuthServersRetries()))
	state.AuthServersTimeout = types.Int64Value(int64(data.GetAuthServersTimeout()))
	state.BandSteer = types.BoolValue(data.GetBandSteer())
	state.BandSteerForceBand5 = types.BoolValue(data.GetBandSteerForceBand5())
	state.Bands = bandsSdkToTerraform(ctx, &diags, data.GetBands())
	state.BlockBlacklistClients = types.BoolValue(data.GetBlockBlacklistClients())
	state.Bonjour = bonjourSdkToTerraform(ctx, &diags, data.GetBonjour())
	state.CiscoCwa = ciscoCwaSdkToTerraform(ctx, &diags, data.GetCiscoCwa())
	state.ClientLimitDown = types.Int64Value(int64(data.GetClientLimitDown()))
	state.ClientLimitDownEnabled = types.BoolValue(data.GetClientLimitDownEnabled())
	state.ClientLimitUp = types.Int64Value(int64(data.GetClientLimitUp()))
	state.ClientLimitUpEnabled = types.BoolValue(data.GetClientLimitUpEnabled())
	state.CoaServers = coaServersSdkToTerraform(ctx, &diags, data.GetCoaServers())
	state.Disable11ax = types.BoolValue(data.GetDisable11ax())
	state.DisableHtVhtRates = types.BoolValue(data.GetDisableHtVhtRates())
	state.DisableUapsd = types.BoolValue(data.GetDisableUapsd())
	state.DisableV1RoamNotify = types.BoolValue(data.GetDisableV1RoamNotify())
	state.DisableV2RoamNotify = types.BoolValue(data.GetDisableV2RoamNotify())
	state.DisableWmm = types.BoolValue(data.GetDisableWmm())
	state.DnsServerRewrite = dnsServerRewriteSdkToTerraform(ctx, &diags, data.GetDnsServerRewrite())
	state.Dtim = types.Int64Value(int64(data.GetDtim()))
	state.DynamicPsk = dynamicPskSdkToTerraform(ctx, &diags, data.GetDynamicPsk())
	state.DynamicVlan = dynamicVlanSdkToTerraform(ctx, &diags, data.GetDynamicVlan())
	state.EnableLocalKeycaching = types.BoolValue(data.GetEnableLocalKeycaching())
	state.EnableWirelessBridging = types.BoolValue(data.GetEnableWirelessBridging())
	state.EnableWirelessBridgingDhcpTracking = types.BoolValue(data.GetEnableWirelessBridgingDhcpTracking())
	state.Enabled = types.BoolValue(data.GetEnabled())
	state.FastDot1xTimers = types.BoolValue(data.GetFastDot1xTimers())
	state.HideSsid = types.BoolValue(data.GetHideSsid())
	state.HostnameIe = types.BoolValue(data.GetHostnameIe())
	state.Hotspot20 = hotspot20SdkToTerraform(ctx, &diags, data.GetHotspot20())
	state.InjectDhcpOption82 = injectDhcpOption82dkToTerraform(ctx, &diags, data.GetInjectDhcpOption82())
	state.Interface = types.StringValue(string(data.GetInterface()))
	state.Isolation = types.BoolValue(data.GetIsolation())
	state.L2Isolation = types.BoolValue(data.GetIsolation())
	state.LegacyOverds = types.BoolValue(data.GetLegacyOverds())
	state.LimitBcast = types.BoolValue(data.GetLimitBcast())
	state.LimitProbeResponse = types.BoolValue(data.GetLimitProbeResponse())
	state.MaxIdletime = types.Int64Value(int64(data.GetMaxIdletime()))
	state.MistNac = mistNacdSkToTerraform(ctx, &diags, data.GetMistNac())
	state.MspId = types.StringValue(data.GetMspId())
	state.MxtunnelIds = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetMxtunnelIds())
	state.MxtunnelName = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetMxtunnelName())
	state.NoStaticDns = types.BoolValue(data.GetNoStaticDns())
	state.NoStaticIp = types.BoolValue(data.GetNoStaticIp())
	state.Portal = portalSkToTerraform(ctx, &diags, data.GetPortal())
	state.PortalAllowedHostnames = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetPortalAllowedHostnames())
	state.PortalAllowedSubnets = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetPortalAllowedSubnets())
	state.PortalApiSecret = types.StringValue(data.GetPortalApiSecret())
	state.PortalDeniedHostnames = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetPortalDeniedHostnames())
	state.PortalImage = types.StringValue(data.GetPortalImage())
	state.PortalSsoUrl = types.StringValue(data.GetPortalSsoUrl())
	state.PortalTemplateUrl = types.StringValue(data.GetPortalTemplateUrl())
	state.Qos = qosSkToTerraform(ctx, &diags, data.GetQos())
	state.Radsec = radsecSkToTerraform(ctx, &diags, data.GetRadsec())
	state.RoamMode = types.StringValue(string(data.GetRoamMode()))
	state.Schedule = scheduleSkToTerraform(ctx, &diags, data.GetSchedule())
	state.SleExcluded = types.BoolValue(data.GetSleExcluded())
	state.Thumbnail = types.StringValue(data.GetThumbnail())
	state.UseEapolV1 = types.BoolValue(data.GetUseEapolV1())
	state.VlanEnabled = types.BoolValue(data.GetVlanEnabled())
	state.VlanId = types.Int64Value(int64(data.GetVlanId()))
	state.VlanIds = vlanIdsSkToTerraform(ctx, &diags, data.GetVlanIds())
	state.VlanPooling = types.BoolValue(data.GetVlanPooling())
	state.WlanLimitDown = types.Int64Value(int64(data.GetWlanLimitDown()))
	state.WlanLimitDownEnabled = types.BoolValue(data.GetWlanLimitDownEnabled())
	state.WlanLimitUp = types.Int64Value(int64(data.GetWlanLimitUp()))
	state.WlanLimitUpEnabled = types.BoolValue(data.GetWlanLimitUpEnabled())
	state.WxtagIds = mist_transform.ListOfStringSdkToTerraform(ctx, data.GetWxtagIds())
	state.WxtunnelId = types.StringValue(data.GetWxtunnelId())
	state.WxtunnelRemoteId = types.StringValue(data.GetWxtunnelRemoteId())
	return state, diags
}
