provider:
  name: mistapi
resources:
  org_evpn_topology:
    create:
      path: /api/v1/orgs/{org_id}/evpn_topologies
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/evpn_topologies/{evpn_topology_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/evpn_topologies/{evpn_topology_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/evpn_topologies/{evpn_topology_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - admin_sso_id
        - site_id
      attributes:
        aliases:
          evpn_topology_id: id
  site_evpn_topology:
    create:
      path: /api/v1/sites/{site_id}/evpn_topologies
      method: POST
    read:
      path: /api/v1/sites/{site_id}/evpn_topologies/{evpn_topology_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/evpn_topologies/{evpn_topology_id}
      method: DELETE
    update:
      path: /api/v1/sites/{site_id}/evpn_topologies/{evpn_topology_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - admin_sso_id
        - site_id
      attributes:
        aliases:
          evpn_topology_id: id
  