provider:
  name: mistapi
resources:
  org_sitegroup:
    create:
      path: /api/v1/orgs/{org_id}/sitegroups
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/sitegroups/{sitegroup_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - site_ids
      attributes:
        aliases:
          sitegroup_id: id