provider:
  name: mistapi
data_sources:
  org_psks:
    read:
      path: /api/v1/orgs/{org_id}/psks
      method: GET
    schema:
      ignores:  
      - site_id   
  site_psks:
    read:
      path: /api/v1/sites/{site_id}/psks
      method: GET
    schema:
      ignores:  
      - max_usage
      - macs