provider:
  name: mistapi
data_sources:
  device_ap_stats:
    read: 
      path: /api/v1/orgs/{org_id}/stats/devices
      method: GET
    schema:
      ignores:
        - evpn_unused
        - evpntopo_id
        - radio_config
        - fields
        - limit
        - page
        - type