provider:
  name: mistapi
resources:
  device_ap:
    create:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    read:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: GET
    delete:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT
    update:
      path: /api/v1/sites/{site_id}/devices/{device_id}
      method: PUT      
    schema:
      ignores:
        - created_time
        - modified_time
        - for_site
        - id
        - iot_config
        - port_config
        - switch_config
        - deviceprofile_id
  org_deviceprofile_ap:
    create:
      path: /api/v1/orgs/{org_id}/deviceprofiles
      method: POST
    read:
      path: /api/v1/orgs/{org_id}/deviceprofiles/{deviceprofile_id}
      method: GET
    delete:
      path: /api/v1/orgs/{org_id}/deviceprofiles/{deviceprofile_id}
      method: DELETE
    update:
      path: /api/v1/orgs/{org_id}/deviceprofiles/{deviceprofile_id}
      method: PUT      
    schema:
      ignores:
      - created_time
      - modified_time
      - for_site
      - iot_config
      - port_config
      - switch_config
      attributes:
        aliases:
          deviceprofile_id: id   